import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


public class stokekrani extends javax.swing.JDialog {

   

    DefaultTableModel modelim;
    stokislemleri islemler = new stokislemleri();
    /**
     * Creates new form stokekrani
     */
    public stokekrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modelim = (DefaultTableModel) stok_tablosu.getModel();
        stokgoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    
    public void stokgoruntule (){
        modelim.setRowCount(0);
        
        ArrayList<stok> stokici = new ArrayList<stok> ();
        
        stokici = islemler.stokgoruntule();
        
        if(stokici != null){
            for(stok stok:stokici){
                Object [] eklenecek = {stok.getId(),stok.getMusted(),stok.getUrun(),stok.getAdet(),stok.getFiyat()};
              modelim.addRow(eklenecek);
            }
        }
        
        
    }
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        anapanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mus_alani = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        urun_alani = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        adet_alani = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fiyat_alani = new javax.swing.JTextField();
        guncelle = new javax.swing.JButton();
        sil = new javax.swing.JButton();
        mesaj = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        urun_ekle = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        stok_tablosu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 51));

        anapanel.setBackground(new java.awt.Color(54, 33, 89));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Tedarikçi Adı");

        mus_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mus_alaniActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Stok İşlemleri");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Ürün Adı");
        jLabel2.setRequestFocusEnabled(false);

        urun_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urun_alaniActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Ürün Sayısı");
        jLabel3.setRequestFocusEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Ürün Fiyatı");

        fiyat_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiyat_alaniActionPerformed(evt);
            }
        });

        guncelle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        guncelle.setForeground(new java.awt.Color(51, 51, 51));
        guncelle.setText("ÜRÜN GÜNCELLE");
        guncelle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });

        sil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sil.setForeground(new java.awt.Color(51, 51, 51));
        sil.setText("ÜRÜN SİL");
        sil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });

        mesaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesajActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("ATAK A.Ş.");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        urun_ekle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        urun_ekle.setForeground(new java.awt.Color(51, 51, 51));
        urun_ekle.setText("YENİ ÜRÜN EKLE");
        urun_ekle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        urun_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urun_ekleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout anapanelLayout = new javax.swing.GroupLayout(anapanel);
        anapanel.setLayout(anapanelLayout);
        anapanelLayout.setHorizontalGroup(
            anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anapanelLayout.createSequentialGroup()
                .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, anapanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mesaj))
                    .addGroup(anapanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(anapanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(urun_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(sil, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(anapanelLayout.createSequentialGroup()
                                .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(34, 34, 34)
                                .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mus_alani)
                                    .addComponent(urun_alani)
                                    .addComponent(adet_alani)
                                    .addComponent(fiyat_alani)))))
                    .addGroup(anapanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(anapanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, anapanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, anapanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        anapanelLayout.setVerticalGroup(
            anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anapanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mus_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(urun_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(adet_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fiyat_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(anapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sil)
                    .addComponent(urun_ekle))
                .addGap(27, 27, 27)
                .addComponent(guncelle)
                .addGap(32, 32, 32)
                .addComponent(mesaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(21, 21, 21))
        );

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("    STOK TABLOSU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        stok_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Tedarikçi", "Ürün Adı", "Ürün Sayısı", "Ürün Fiyatı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        stok_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stok_tablosuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(stok_tablosu);
        if (stok_tablosu.getColumnModel().getColumnCount() > 0) {
            stok_tablosu.getColumnModel().getColumn(0).setResizable(false);
            stok_tablosu.getColumnModel().getColumn(1).setResizable(false);
            stok_tablosu.getColumnModel().getColumn(2).setResizable(false);
            stok_tablosu.getColumnModel().getColumn(3).setResizable(false);
            stok_tablosu.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(anapanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anapanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fiyat_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiyat_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fiyat_alaniActionPerformed

    private void urun_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urun_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urun_alaniActionPerformed

    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleActionPerformed
        // TODO add your handling code here:
        
        String musted = mus_alani.getText();
        String urun = urun_alani.getText();
        String adet = adet_alani.getText();
        String fiyat = fiyat_alani.getText();
        
        int selectedrow  = stok_tablosu.getSelectedRow();
        
        if(selectedrow==-1){
            
            if(modelim.getRowCount()==0){
                
                mesaj.setText("Stok Tablosu Boş");
            }else{
                
                mesaj.setText("Güncellenecek Ürünü Seçin");
            }
            
        }else{
            
            int id =(int) modelim.getValueAt(selectedrow, 0);
            
            islemler.urunguncelle(id,musted,urun,adet,fiyat);
            stokgoruntule();
            mesaj.setText("Ürün Güncellendi..");
        }
    }//GEN-LAST:event_guncelleActionPerformed

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        // TODO add your handling code here:
        
        mesaj.setText("");
        
        int selectedrow = stok_tablosu.getSelectedRow();
        
        if(selectedrow == -1){
            
            if(modelim.getRowCount()==0){
                
                mesaj.setText("Çalışan Tablosu Boş");
            }else{
                mesaj.setText("Lütfen Silinecek Ürünü Seçin");
            }
            
        }else{
            
            int id = (int)modelim.getValueAt(selectedrow, 0);
            islemler.urunusil(id);
            stokgoruntule();
            
        }
        
    }//GEN-LAST:event_silActionPerformed

    private void mus_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mus_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mus_alaniActionPerformed

    private void mesajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesajActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesajActionPerformed

    private void urun_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urun_ekleActionPerformed
        // TODO add your handling code here:
        mesaj.setText("");
        
        String musted = mus_alani.getText();
        String urun = urun_alani.getText();
        String adet = adet_alani.getText();
        String fiyat = fiyat_alani.getText();
        
       islemler.urunekle(musted, urun, adet, fiyat);
        
        stokgoruntule();
        
        mesaj.setText("Yeni Üürn Başarıyla Eklendi");
    }//GEN-LAST:event_urun_ekleActionPerformed

    private void stok_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stok_tablosuMouseClicked
        // TODO add your handling code here:
        
        int selectedrow = stok_tablosu.getSelectedRow();
        
        mus_alani.setText(modelim.getValueAt(selectedrow, 1).toString());
        urun_alani.setText(modelim.getValueAt(selectedrow, 2).toString());
        adet_alani.setText(modelim.getValueAt(selectedrow, 3).toString());
        fiyat_alani.setText(modelim.getValueAt(selectedrow, 4).toString());
        
    }//GEN-LAST:event_stok_tablosuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stokekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stokekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stokekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stokekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                stokekrani dialog = new stokekrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adet_alani;
    private javax.swing.JPanel anapanel;
    private javax.swing.JTextField fiyat_alani;
    private javax.swing.JButton guncelle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField mesaj;
    private javax.swing.JTextField mus_alani;
    private javax.swing.JButton sil;
    private javax.swing.JTable stok_tablosu;
    private javax.swing.JTextField urun_alani;
    private javax.swing.JButton urun_ekle;
    // End of variables declaration//GEN-END:variables
}
